name: Daily Commit Job

on:
  schedule:
    - cron: '17 9 * * *'  # Every day at 09:17 UTC
  workflow_dispatch:

permissions:
  contents: write  # ✅ required to allow git push

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update file with timestamp - 21f3003091@ds.study.iitm.ac.in
        run: |
          echo "Updated on $(date -u)" >> daily-log.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily update from GitHub Action" || echo "No changes to commit"
          git push
